cleanup shell script
Signed-off-by: Adam Stokes <battlemidget@users.noreply.github.com>

diff --git a/kubernetes b/kubernetes
--- a/kubernetes
+++ b/kubernetes
@@ -1,4 +1,4 @@
-#!/usr/bin/python3
+#!/bin/bash
 #
 # Ubuntu installer for Kubernetes
 #
@@ -15,25 +15,51 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-import argparse
-import sys
 
-try:
-    option = sys.argv[1]
-except IndexError:
-    print("Unknown argument, please use `help` or `install`.")
-    sys.exit(1)
+args=("$@")
 
-if option not in ['help', 'install']:
-    print(
-        "Unknown argument: {}, please use `help` or `install`".format(option))
-    sys.exit(1)
+usage() {
+    echo "This is the standard Ubuntu installer for Kubernetes that supports your "
+    echo "workstation, VMware, Openstack, AWS, Azure, Google, and Oracle cloud. "
+    echo "Deploy a K8s instance with 'kubernetes install'"
+}
 
-if option == 'help':
-    print("This is the standard Ubuntu installer for Kubernetes that supports "
-          "your workstation, vmware, openstack, AWS, Azure, Google, and Oracle "
-          "cloud. Deploy a K8s instance with `kubernetes install`")
-    sys.exit(0)
-else:
-    print("Fetching components..")
-    sys.exit(0)
+case ${args[0]} in
+    help)
+        usage
+        exit 0
+        ;;
+    install)
+        PS3='Please choose an installation option: '
+        options=("microk8s" "Canonical Distribution of Kubernetes" "Quit")
+        select opt in "${options[@]}"
+        do
+            case $opt in
+                "microk8s")
+                    echo "Fetch components..."
+                    echo "sudo snap install microk8s --beta --classic"
+                    break
+                    ;;
+                "Canonical Distribution of Kubernetes")
+                    echo "Fetching components..."
+                    echo "sudo snap install conjure-up --classic"
+                    echo "conjure-up canonical-kubernetes"
+                    break
+                    ;;
+                "Quit")
+                    echo "Exiting..."
+                    break
+                    ;;
+                *)
+                    echo "Invalid option"
+                    ;;
+            esac
+        done
+        exit 0
+        ;;
+    *)
+        echo "Unknown arguments: ${args[@]}"
+        usage
+        exit 1
+        ;;
+esac
